server:
  port: 9099
  
spring:
  application:
    name: marketplace-frontend
  
eureka:
  instance:
    prefer-ip-address: true
    appname: marketplace
  client:
    service-url:
      #DEV
      #defaultZone: http://localhost:9080/eureka/
      #Docker
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true
    