server:
  port: 9091

spring:
  application:
    name: sale
  jpa:
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysqlserver-saledb:3307/saledb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
    appname: sale
    
  client:
    service-url:
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true