server:
  port: 9094
  
spring:
  application:
    name: product-category
  jpa:
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql:///mysqlserver-product_categorydb:3309/product_categorydb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
    appname: product_category
    
  client:
    service-url:
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true