server:
  port: 9095
  
spring:
  application:
    name: product-notes
  jpa:
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    #DEV
    #url: jdbc:mysql://localhost:3311/productnotedb?allowPublicKeyRetrieval=true&sslMode=DISABLED
    #Docker
    url: jdbc:mysql://mysqlserver-productnotedb:3311/productnotedb?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
    appname: product_note
    
  client:
    service-url:
      #DEV
      #defaultZone: http://localhost:9080/eureka/
      #Docker
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true
    