server:
  port: 8080

spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
  endpoint:
    routes:
      enabled: true
      

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

ribbon: 
  ConnectTimeout: 10000
  ReadTimeout: 10000
      
zuul:
  ignoredServices: "*"
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-per-route-connections: 10000
    max-total-connections: 5000
  semaphore:
    max-semaphores: 500
  ribbon:
    eager-load:
      enabled: true
  routes:
    customer: 
      path: /customer/**
      serviceId: customer
    product: 
      path: /product/**
      serviceId: product
    sale: 
      path: /sale/**
      serviceId: sale
    salesman: 
      path: /salesman/**
      serviceId: salesman
    product-note: 
      path: /product_note/**
      serviceId: product-note
    product_category: 
      path: /product_category/**
      serviceId: product_category

eureka:
  instance:
    prefer-ip-address: true
    appname: gateway   
  client:
    service-url:
      #DEV
      defaultZone: http://localhost:9080/eureka/
      #Docker
      #defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true