server:
  port: 9093
  
spring:
  application:
    name: customer
  jpa:
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    #DEV
    #url: jdbc:mysql://localhost:3308/customerdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    #Docker
    url: jdbc:mysql://mysqlserver-customerdb:3308/customerdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
    appname: customer
  client:
    service-url:
      #DEV
      #defaultZone: http://localhost:9080/eureka/
      #Docker
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true
    