server:
  port: 9090
  
spring:
  application:
    name: product
  jpa:
    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    #DEV
    url: jdbc:mysql://localhost:3306/productdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    #Docker
    #url: jdbc:mysql://mysqlserver-productdb:3306/productdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true
    
eureka:
  instance:
    prefer-ip-address: true
    appname: product
    
  client:
    service-url:
      #DEV
      defaultZone: http://localhost:9080/eureka/
      #Docker
      #defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true
  