server:
  port: 9092

spring:
  application:
    name: salesman
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://mysqlserver-salesmandb:3310/salesmandb?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
    appname: salesman
    
  client:
    service-url:
      defaultZone: http://discovery-eureka:9080/eureka/
    register-with-eureka: true
    fetch-registry: true
